//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidaturas
    {
        public int Codigo_candidatura { get; set; }
        public int Codigo_usuario { get; set; }
        public int Codigo_vaga { get; set; }
        public int Status_candidatura { get; set; }
    }
}
