//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculo
    {
        public int codigo_curriculo { get; set; }
        public string campo_a { get; set; }
        public string campo_b { get; set; }
        public int codigo_user { get; set; }
    }
}
