//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblA
    {
        public int Id { get; set; }
        public int Cod_user { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string imageUrl { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
