//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vagas
    {
        public int Codigo_vaga { get; set; }
        public string Vaga { get; set; }
        public string Vaga_descricao { get; set; }
    }
}
